### ISSUE TITLE
athena-osint Suggestion 

### ISSUE THREAD

**Issue by PardesiCat** [Athena-OS/athena-repository#5]
in **athena-osint** 

we use the tool name  **creepy**  [current in use](https://github.com/ilektrojohn/creepy)

but that is outdated in Blackarch repo (last updated in 2014)  insead if we pack 

this updated of [creepy](https://github.com/jkakavas/creepy) it will be good

**Comment by D3vil0p3r** [comment]
The updated is not maintained anymore and not maintained tools will be removed by BA repository. creepy currently is also in the [broken](https://github.com/BlackArch/blackarch/blob/master/lists/broken) list of BlackArch tools.
